
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Feb 03 00:48:49 COT 2023
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Float = 3;
  public static final int Parentesis_c = 8;
  public static final int ERROR = 16;
  public static final int Parentesis_a = 7;
  public static final int EOF = 0;
  public static final int Comita = 12;
  public static final int Int = 2;
  public static final int Linea = 6;
  public static final int Llave_c = 10;
  public static final int Identificador = 14;
  public static final int Main = 11;
  public static final int error = 1;
  public static final int Llave_a = 9;
  public static final int Void = 5;
  public static final int Numero = 15;
  public static final int P_Coma = 13;
  public static final int Double = 4;
}

